#!/bin/bash

# Source env_vars file.
[ -f ~/.config/bash/env_vars ] && source ~/.config/bash/env_vars

# Source personal aliases.
[ -f "$SMLSS_PERSONAL_ALIASES" ] && source "$SMLSS_PERSONAL_ALIASES"

# Alias definitions.


alias ls='ls --color=auto'
alias l='ls -CAF'
alias ll='ls -AlhF'

alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias info='info --vi-keys'

alias py='python3'

alias cl='clear; l'

# Sorted list of biggest files/directories in current directory.
alias dh="du -hd 1 | sort -h"

alias v='nvim'

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gk='git checkout'
alias gl='git log'
alias gp='git push'
alias gpa='git remote | xargs -I x git push x'
alias gpl='git pull'
alias gr='git restore'
alias gra="git status | grep '^[^a-z]*modified' | awk '{ print \$2 }' |
	xargs git restore"
alias gre='git remote -v'
alias grl='git reflog'
alias gs='git status'
alias gsl='git shortlog'
alias gsh='git show --format=fuller'
alias gt='git tag'

alias f='new firefox'
alias s='new sxiv'
alias x='new xournalpp'
alias z='new zathura'

alias yay='yay --sudoloop' # prevents sudo timeout on long builds

# Sums up numbers on each line in standard input
alias count='paste -sd+ - | bc'

alias sp='sudo protonvpn'

