#!/bin/bash

# Source env_vars file.
[ -f ~/.config/bash/env_vars ] && source ~/.config/bash/env_vars

# Source personal aliases.
[ -f "$SMLSS_PERSONAL_ALIASES" ] && source "$SMLSS_PERSONAL_ALIASES"

# Alias definitions.


alias ls='ls --color=auto'
alias l='ls -CAF'
alias ll='ls -AlhF'

alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias info='info --vi-keys'

alias py='python3'

alias cl='clear; l'

# Sorted list of biggest files/directories in current directory. Only lists
# items in current directory -- that's what the grep does (removing anything
# with more than one directory level to it)
alias dh="du -h | sort -h | grep -v '.*/.*/.*'"

alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias ed='ed -p:'

alias r='ranger'

alias dba="nvim $SMLSS_DIR/dots/bash/aliases"
alias dbe="nvim $SMLSS_DIR/dots/bash/env_vars"

alias cs="cd $SMLSS_DIR && pwd && git status && l"

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gk='git checkout'
alias gl='git log'
alias gp='git push'
alias gr='git restore'
alias gre='git remote -v'
alias grl='git reflog'
alias gs='git status'
alias gsl='git shortlog'
alias gsh='git show'
alias gt='git tag'


alias f='firefox'
alias z='zathura'

alias yay='yay --sudoloop' # prevents sudo timeout on long builds

# Sums up numbers on each line in standard input
alias count='paste -sd+ - | bc'

