#!/bin/bash

# Alias definitions.

alias ls='ls --color=auto'
alias l='ls -CAF'
alias ll='ls -AlhF'

alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias info='info --vi-keys'

alias py='python3'

alias cl='clear; l'

# Sorted list of biggest files/directories in current directory. Only lists
# items in current directory -- that's what the grep does (removing anything
# with more than one directory level to it)
alias dh="du -h | sort -h | grep -v '.*/.*/.*'"

alias v='nvim'
alias vi='nvim'
alias ed='ed -p:'

alias r='ranger'

alias dba='cd ~/smlss; nvim dots/bash/aliases'
alias dbe='cd ~/smlss; nvim dots/bash/env_vars'

alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gt='git tag'
alias gp='git push'
alias gr='git remote'
alias gd='git diff'
alias gl='git log'
alias gsh='git show'
alias gb='git branch'
alias gk='git checkout'


alias f='firefox'
alias z='zathura'

alias yay='yay --sudoloop' # prevents sudo timeout on long builds

# Sums up numbers on each line in standard input
alias count='paste -sd+ - | bc'

